version: "3.9"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/sonarr:/config
      - media:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/radarr:/config
      - media:/data
    ports:
      - 7878:7878
    restart: unless-stopped

networks:
  reverse-proxy:
    external: true
    
volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/Media/"
