version: "3.9"

services:
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:4.2.3
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
      - UMASK=002
    volumes:
      - /mnt/user/services/servarr/sabnzbd:/config
      - /mnt/user/Media/Usenets:/data/Usenets
    ports:
      - "8081:8080"
    networks:
     - reverse-proxy
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/lidarr:/config
      - media:/data
    ports:
      - 8686:8686
    networks:
     - reverse-proxy
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/sonarr:/config
      - media:/data
    ports:
      - 8989:8989
    networks:
     - reverse-proxy
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/radarr:/config
      - media:/data
    ports:
      - 7878:7878
    networks:
     - reverse-proxy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
     - reverse-proxy

networks:
  reverse-proxy:
    external: true
    
volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/Media/"
#gluetun:
    #image: qmcgaw/gluetun:latest
    #cap_add:
     #- NET_ADMIN
    #devices:
     #- /dev/net/tun
    #networks:
     #- vpn
    #environment:
      #TZ: America/Chicago
      #VPN_SERVICE_PROVIDER: custom
     # VPN_TYPE: wireguard
      #OPENVPN_CUSTOM_CONFIG: /gluetun/custom.conf
    #volumes:
     #Wireguard configuration file on host is in ./glueton/wireguard/wg0.conf
    #  - /mnt/user/services/servarr/gluetun:/gluetun
   # networks:
    # - reverse-proxy


  #deluge:
    #image: lscr.io/linuxserver/deluge:latest
    #networks:
     #- vpn
    #environment:
      #- PUID=99
      #- PGID=100
      #- TZ=America/Chicago
      #- DELUGE_LOGLEVEL=error #optional
    #volumes:
      #- /mnt/user/services/servarr/deluge/config:/config
      #- /mnt/user/Media/Torrents:/downloads
    #ports:
      #- 8112:8112
      #- 6881:6881
      #- 6881:6881/udp
      #- 58846:58846 #optional
