version: "3.9"

services:
  gluetun:
    image: qmcgaw/gluetun:latest
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    environment:
      TZ: America/Chicago
      VPN_SERVICE_PROVIDER: custom
      VPN_TYPE: wireguard
      #Bind mounting the configuration file instead of populating environment variables
      #- VPN_ENDPOINT_IP:
      #- VPN_ENDPOINT_PORT:
      #- WIREGUARD_PUBLIC_KEY:
      #- WIREGUARD_PRIVATE_KEY:
      #- WIREGUARD_PRESHARED_KEY:
      #- WIREGUARD_ADDRESSES:
    volumes:
     #Wireguard configuration file on host is in ./glueton/wireguard/wg0.conf
      - /mnt/user/services/servarr/gluetun:/gluetun
   # networks:
    # - reverse-proxy
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    #container_name: deluge
    #network_mode: "service:glueton"
    environment:
      - PUID=99
      - PGID=100
      - TZ=America/Chicago
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - /mnt/user/services/servarr/deluge/config:/config
      - /mnt/user/Media/Torrents:/downloads
      #- /mnt/user/Media/:/unraid
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
      - 58846:58846 #optional
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/sonarr:/config
      - media:/data
    ports:
      - 8989:8989
    networks:
     - reverse-proxy
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/radarr:/config
      - media:/data
    ports:
      - 7878:7878
    networks:
     - reverse-proxy
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /mnt/user/services/servarr/prowlarr:/config
    ports:
      - "9696:9696"
    networks:
     - reverse-proxy

networks:
  reverse-proxy:
    external: true
    
volumes:
  media:
    driver: local
    driver_opts:
      type: "nfs"
      o: "addr=unraid.lan,rw,hard"
      device: ":/mnt/user/Media/"
