name: 'servarr'
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test-runner:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
      - name: Run a container command
        env:
          PLEX_CLAIM: ${{ secrets.PLEX_CLAIM }}
        run: |
          docker stack deploy -c servarr.yaml arr
